apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: ic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ic-webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - image: mclab7/ic-webapp:1.0
        name: ic-webapp
        ports:
          - containerPort: 8080
        env:
        - name: ODOO_URL
          value: http://$HOST_IP:30030
        - name: PGADMIN_URL
          value: http://$HOST_IP:30200
---
apiVersion: v1
kind: Service
metadata:
  name: ic-service
  namespace: ic
spec:
  selector:
    app: ic-webapp
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
