version: '3.3'
services:
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        networks:
            - ic_network
        environment:
            - 'PGADMIN_DEFAULT_EMAIL=pgadmin@admin.com'
            - 'PGADMIN_DEFAULT_PASSWORD=pgadmin'
        ports:
            - "5050:80"
        volumes:
            - '/pgadmin-servers/servers.json:/pgadmin4/servers.json'
            - 'pgadmin_data:/var/lib/pgadmin'
    ic-webapp:
        container_name: ic-webapp
        ports:
            - "5008:8080"
        environment:
            - "ODOO_URL=http://$HOST_IP:8069"
            - "PGADMIN_URL=http://$HOST_IP:5050"
        image: 'mclab7/ic-webapp:1.0'
        networks:
            - ic_network
    postgres:
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_DB=postgres
        networks:
            - ic_network
        volumes:
            - 'pgdata:/var/lib/postgresql/data'
        container_name: postgres
        image: 'postgres:13'
        ports:
            - '5432:5432'
    odoo:
        depends_on:
            - postgres
        ports:
            - '8069:8069'
        container_name: odoo
        networks:
            - ic_network
        volumes:
            - '/config:/etc/odoo'
            - '/addons:/mnt/extra-addons'
            - '/odoo-web-data:/var/lib/odoo'
        environment:
            - USER=odoo
            - PASSWORD=odoo
            - HOST=postgres
        image: odoo
volumes:
    pgdata:
    pgadmin_data:
networks:
    ic_network:
      driver: bridge
      name: ic_network
